<div class="collection-options-wrapper">
    <b>
        <div id="pt-click" class="col-opt">
            <span class="popup-arrow-right">&#9658;</span>
            <span class="popup-arrow-down">&#9660;</span>
            MAIN COLOR
        </div>
        <div id="pt-popup" class="col-opt-child">
            <div class="color-picker-wrapper">
                <div style="display: none" class="color-filters-active" data-bread=""></div>
                <div class="color-filters" id="color-picker-color-white" data-color="white" data-bread=" > WHITE"></div>
                <div class="color-filters" id="color-picker-color-black" data-color="black" data-bread=" > BLACK"></div>
                <div class="color-filters" id="color-picker-color-red" data-color="red" data-bread=" > RED"></div>
                <div class="color-filters" id="color-picker-color-blue" data-color="blue" data-bread=" > BLUE"></div>
                <div class="color-filters" id="color-picker-color-green" data-color="green" data-bread=" > GREEN"></div>
                <div class="color-filters" id="color-picker-color-colored" data-color="colored" data-bread=" > COLORED"></div>
                <br />
                <div class="color-filters" id="color-picker-color-gray" data-color="gray" data-bread=" > GRAY"></div>
                <div class="color-filters" id="color-picker-color-brown" data-color="brown" data-bread=" > BROWN"></div>
                <div class="color-filters" id="color-picker-color-orange" data-color="orange" data-bread=" > ORANGE"></div>
                <div class="color-filters" id="color-picker-color-light blue" data-color="lightblue" data-bread=" > LIGHT BLUE"></div>
                <div class="color-filters" id="color-picker-color-yellow" data-color="yellow" data-bread=" > YELLOW"></div>
                <div class="color-filters" id="color-picker-color-pink" data-color="pink" data-bread=" > PINK"></div>
            </div>
        </div>
    </b>
</div>
<script type="text/javascript">

</script>