<div class="collection-options-wrapper">
    <b>
        <div id="pt-click" class="col-opt">
            <span class="popup-arrow-right">&#9658;</span>
            <span class="popup-arrow-down">&#9660;</span>
            PRICE
        </div>
        <div id="pt-popup" class="col-opt-child">
            <ul>
                <li class="price-filters-active" data-bread=""></li>
                <li id="asc" class="price-filters" data-bread=" > FROM LOW PRICE">&nbsp;<span>FROM LOW</span></li>
                <li id="desc" class="price-filters" data-bread=" > FROM HI PRICE">&nbsp;<span>FROM HI</span></li>
                <li id="like" class="price-like-filters" data-bread=" > EXACT PRICE">&nbsp;<input type="number " size="10" placeholder="EXACT PRICE, $" /></li>
            </ul>
            <?=$this->partial('collection/collection/partial/price-slider.phtml');?>
        </div>
    </b>
</div>