<?php //die(var_dump($details));?> <!--in case of forgotten income array's fields names - uncomment-->
<!-- TO-CART-CONFIRM -->
<div id="collection-overlay"></div>
<div id="to-cart-confirm"></div>
<table id="item-detailes-table">
    <tr>
        <td id="item-details-img-td" rowspan="4" style="background-image: url(<?php echo Collection\Model\Collection::COLL_IMG_PATH.$details->img_link;?>);">
            <div id="is-in-cart-img"><img src="<?=$this->is_in_cart;?>" /></div>
            <!--<img id="item-details-img" src="<?php echo Collection\Model\Collection::COLL_IMG_PATH.$details->img_link;?>" />-->
            <div></div>
        </td>
        <td rowspan="4">
            <?php
                foreach($img_s as $img_link){
                    echo '<div class="item-details-img-preview"><img src="'.Collection\Model\Collection::COLL_IMG_PATH.$img_link.'" /></div>';
                }
            ;?>
        </td>
        <td align="center">
            <h2><?=$details->item_name;?></h2><br />
            <a href="<?=$this->url('order', array('controller' => 'order', 'action' => 'index'))?>">
                <div class="btn btn-success pull">Buy this one as single</div>
            </a>
            <div id="this-to-cart-" class="btn btn-success pull" data-num="<?=$details->item_id;?>">Add to cart</div>
            <a href="<?=$this->url('collection', array());?>">
                <div class="btn btn-success pull">Back to main showcase</div>
            </a>
        </td>
    </tr>
        <tr><td align="center"><h2><?=$details->item_price;?>&nbsp;$</h2></td></tr>
        <tr><td>quantity to order:</td></tr>
        <tr><td>shipping policy</td></tr>
</table>




