<?php
$title = 'Register';
$this->headTitle($title);
?>
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
</head>
<body>
<section class="register">
    <h2>New one in MyStore</h2>
    <?php if ($this->error): ?>
        <p class="error">
            There were one or more issues with your submission.
            Please correct them as indicated below.
        </p>
    <?php endif ?>
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array(
        'controller'=>'Registration',
        'action' => 'process'
    )));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>
    <table>
        <tr><td></td></tr>
        <tr>
            <td>
                <?=$this->formRow($form->get('user_name'));?>
            </td>
        </tr>
        <tr>
            <td>
                <?=$this->formRow($form->get('user_email'));?>
            </td>
        </tr>
        <tr>
            <td>
                <?=$this->formRow($form->get('user_password'));?>
            </td>
        </tr>
        <tr>
            <td>
                <?=$this->formRow($form->get('confirm_password'));?>
            </td>
        </tr>
        <tr><td></td></tr>
    </table>
    <?php
    echo $this->formElement($form->get('submit')->setAttribute('class','btn btn-success pull'));
    echo $this->formElementErrors($form->get('submit'));
    ?>
    <?php echo $this->form()->closeTag($form);?>
</section>
</body>
</html>