<?php
$title = 'Registration';
$this->headTitle($title);
$flash = $this->flashMessenger();
?>
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
</head>
<body>
<section class="register">
    <h2>New one in MyStore</h2>
<?php if ($this->error): ?>
        <p class="error">
            There were one or more issues with your submission.
            Please correct them as indicated below.
        </p>
<?php endif;
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array(
        'controller'=>'Registration',
        'action' => 'process'
    )));
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('user_name')).'<br />';
    echo $this->formRow($form->get('user_email')).'<br />';
    echo $this->formRow($form->get('user_password')).'<br />';
    echo $this->formRow($form->get('confirm_password')).'<br />';
    echo $this->formRow($form->get('submit')->setAttribute('class','btn btn-success pull'));
    echo $this->form()->closeTag($form);
?>
</section>
</body>
</html>