<a href="<?php echo $this->url('collection-manager',
    array('action'=>'add-form-view', 'id' => $item->item_id));?>"> [ add single item ] </a>
<a href=""> [ add list of items ] </a>
<a href=""> [ update stock ] </a>
<hr />
<table id="tableGoods-adm">
    <th>id</th>
    <th>name</th>
    <th>view</th>
    <th>price</th>
    <th>quantity</th>
    <th>action</th>
<?php foreach ($collection as $item) : ?>
    <tr>
        <td><!-- id -->
            <?php echo $item->item_id ;?>
        </td>
        <td><!-- name -->
            <?php echo $item->item_name ;?>
        </td>
        <td><!-- view -->
            <img src= "<?php echo  Admin\Model\AdminCollection::COLL_IMG_PATH.$this->escapeHtml($item->img_link);?>" />
        </td>
        <td><!-- price -->
            <?php echo $item->item_price ;?>
        </td>
        <td><!-- quantity -->
            <?php echo $item->item_quantity ;?>
        </td>
        <td><!-- action -->
            <span class="zf-midnightblue"><a href="<?php echo $this->url('collection-manager',
                    array('action'=>'edit-view', 'id' => $item->item_id));?>">[ edit ]</a></span><br />
            <span class="zf-midnightblue"><a href="<?php echo $this->url('collection-manager',
                    array('action'=>'delete', 'id' => $item->item_id));?>">[ delete ]</a></span>
        </td>
    </tr>
<?php endforeach; ?>
</table>