<?php
$title = 'Register';
$this->headTitle($title);
?>
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
</head>
<body>
<section class="register">
    <h2>New one in MyStore</h2>
    <?php if ($this->error): ?>
        <p class="error">
            There were one or more issues with your submission.
            Please correct them as indicated below.
        </p>
    <?php endif ?>
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array(
        'controller'=>'Register', 'action' => 'process'
    )));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>
        <dl class="zend_form">
            <dt><?php echo $this->formLabel($form->get('user_name')); ?></dt>
            <dd><?php
                echo $this->formElement($form->get('user_role'));
                echo $this->formElement($form->get('user_name'));
                echo $this->formElementErrors($form->get('user_name'));
                ?></dd>
            <dt><?php echo $this->formLabel($form->get('user_email')); ?>
            </dt>
            <dd><?php
                echo $this->formElement($form->get('user_email'));
                echo $this->formElementErrors($form->get('user_email'));
                ?></dd>
            <dt><?php echo $this->formLabel($form->get('user_password'));
                ?></dt>
            <dd><?php
                echo $this->formElement($form->get('user_password'));
                echo $this->formElementErrors($form->get('user_password'));
                ?></dd>
            <dt><?php echo $this->formLabel($form->get('confirm_password'));
                ?></dt>
            <dd><?php
                echo $this->formElement($form->get('confirm_password'));
                echo $this->formElementErrors($form->get('confirm_password'));
                ?></dd>
            <dd><?php
                echo $this->formElement($form->get('submit')->setAttribute('class','btn btn-success pull'));
                echo $this->formElementErrors($form->get('submit'));
                ?></dd>
        </dl>
    <?php echo $this->form()->closeTag($form);?>
</section>
</body>
</html>