<?php
$flash = $this->flashMessenger();
?>
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>add new</title>
</head>
<body>
<section class="add">
    <h2><a href="<?php echo $this->url('user-manager', array(
        'controller'=>'Index', 'action' => 'index'));?>">
        <img src="<?php echo $this->basePath('img/back-img-2.png');?>" />
    </a> |
    Add new user</h2><?php //echo $flash->render('NotAdd') ;?>
    <?php if ($this->error): ?>
        <p class="error">
            There were one or more issues with your submission.
            Please correct them as indicated below.
        </p>
    <?php endif ?>
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url('user-manager', array(
        'controller'=>'UserManager',
        'action' => 'processAdd'
    )));
    $form->setAttribute('method', 'post');
    echo $this->form()->openTag($form);
    ?>
    <dl class="zend_form">
        <dt><?php echo $this->formLabel($form->get('user_name')); ?>
        </dt>
        <dd><?php
            echo $this->formElement($form->get('user_name'));
            echo $this->formElementErrors($form->get('user_name'));
            ?></dd>
        <dt><?php echo $this->formLabel($form->get('user_email')); ?>
        </dt>
        <dd><?php
            echo $this->formElement($form->get('user_email'));
            echo $this->formElementErrors($form->get('user_email'));
            ?></dd>
        <dt><?php echo $this->formLabel($form->get('user_password'));
            ?></dt>
        <dd><?php
            echo $this->formElement($form->get('user_password'));
            echo $this->formElementErrors($form->get('user_password'));
            ?></dd>
        <dt><?php echo $this->formLabel($form->get('user_role'));
            ?></dt>
        <dd><?php
            echo $this->formElement($form->get('user_role'));
            echo $this->formElementErrors($form->get('user_role'));
            ?></dd>
        <dd><?php
            echo $this->formElement($form->get('add')->setAttribute('class','btn btn-success pull-left'));
            echo $this->formElementErrors($form->get('add'));
            ?></dd>
    </dl>
    <?php echo $this->form()->closeTag($form);?>
<?php
    echo $flash->render('duplicate', array(
        'alert', 'alert-dismissable', 'alert-danger'
    ));
?>
</section>
</body>
</html>