<?php

$this->headScript()->appendFile('http://code.jquery.com/jquery-1.8.3.js','text/javascript');
$this->headScript()->appendFile('http://code.jquery.com/ui/1.10.0/jquery-ui.js','text/javascript');
// Подключение стилей из библиотеки jQuery UI
$this->headLink()->appendStylesheet('http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css');

$title = 'My store';
$this->headTitle($title);
?>
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h1>Welcome to My Store - Kirill's test task </h1>
    <a class="btn btn-success pull" href="/users/login">Login</a>
    <a class="btn btn-success pull" href="/users/register">Registration</a>
    <?php echo $this->collection;?>
</body>
</html>