<table id="main-table">
    <tr>
        <td colspan="2">
                <div id="mi-slider" class="mi-slider">

                </div>
        </td>
    </tr>
    <tr>
        <td>
            <a href="/collection">
                <img src="/img/flbtf080615a-jordancasual.jpg" />
                <div class="main-table-banner-text">JORDAN SPORT & CASUAL</div>
            </a>
        </td>
        <td>
            <img src="/img/flbtf080615a-nikebasketball3.jpg" />
            <div class="main-table-banner-text">NIKE BASKETBALL</div>
        </td>
    </tr>

    <tr>
        <td>
            <img src="/img/flbtf080615a-adioriginals.jpg" />
            <div class="main-table-banner-text">ADIDAS ORIGINALS</div>
        </td>
        <td>
            <img src="/img/flbtf080615a-hats.jpg" />
            <div class="main-table-banner-text">HATS</div>
        </td>
    </tr>
</table>