<table id="main-table">
    <tr>
        <td colspan="2">
                <div id="mi-slider" class="mi-slider">
                    <ul>
                        <li><a href="#"><img src="slider/ItemSlider/images/1.jpg" /></a></li>
                    </ul>
                    <ul>
                        <li><a href="#"><img src="/slider/ItemSlider/images/2.jpg" /></a></li>
                    </ul>
                    <ul>
                        <li><a href="#"><img src="/slider/ItemSlider/images/3.png" /></a></li>

                    </ul>
                    <ul>
                        <li><a href="#"><img src="/slider/ItemSlider/images/4.png" /></a></li>
                    </ul>
                    <nav>
                        <a href="#">Jordan</a>
                        <a href="#">Adidas</a>
                        <a href="#">Nike</a>
                        <a href="#">KD 8 Collection</a>
                    </nav>
                </div>
        </td>
    </tr>
    <tr>
        <td>
            <img src="/img/flbtf080615a-jordancasual.jpg" />
            <div class="main-table-banner-text">JORDAN CASUAL</div>
        </td>
        <td>
            <img src="/img/flbtf080615a-nikebasketball3.jpg" />
            <div class="main-table-banner-text">NIKE BASKETBALL</div>
        </td>
    </tr>

    <tr>
        <td>
            <img src="/img/flbtf080615a-adioriginals.jpg" />
            <div class="main-table-banner-text">ADIDAS ORIGINALS</div>
        </td>
        <td>
            <img src="/img/flbtf080615a-hats.jpg" />
            <div class="main-table-banner-text">HATS</div>
        </td>
    </tr>
</table>