<!--NOTICE: data provider - IndexController::indexAction()  -->
<table class="admin-table">
    <tr>
        <td>
            <h1>NOW IN CARTS</h1>
        </td>
        <td><h1>:</h1></td>
        <td>
            <h1><span class="admin-informer"><?=$this->now_in_carts;?></span></h1>
        </td>
    </tr>
    <tr>
        <td>
            <h1>NOW IN ORDERS</h1>
        </td>
        <td><h1>:</h1></td>
        <td>
            <h1><span class="admin-informer"><?=0;?></span></h1>
        </td>
    </tr>
    <tr>
        <td>
            <h1>SIGNED USERS</h1>
        </td>
        <td><h1>:</h1></td>
        <td>
            <h1><span class="admin-informer"><?=$this->signed_users;?></span></h1>
        </td>
    </tr>
    <tr>
        <td>
            <h1>SALES LEADER</h1>
        </td>
        <td><h1>:</h1></td>
        <td>
            <h1><span class="admin-informer"><??></span></h1>
        </td>
    </tr>
</table>

