<?=$this->ref;?>
<?php
    $form = $this->order_form;
    $form->setAttribute('action', $this->url(null ,array('controller'=>'index','action'=>'process')));
    $form->prepare();
    echo $this->form()->openTag($form);
?>
    <input type="hidden" name="cart_id" value="<?=$this->cart_id;?>" />
<table id="order-table" cellpadding="0">
    <th>
        <h1><span class="zf-green">step1: </span><br /><span>Your profile</span></h1>
    </th>
    <th></th>
    <th>
        <h1><span class="zf-green">step2: </span><br /><span>Check your order</span></h1>
    </th>
    <th></th>
    <th>
        <h1><span class="zf-green">step3: </span><br /><span>Payment</span></h1>
    </th>
    <th></th>
    <tr>
        <td class="order-step-line" width="250px"></td>
        <td>
            <img src="/img/10-qwe-01.png" />
        </td>
        <td class="order-step-line"  width="250px"></td>
        <td>
            <img src="/img/10-qwe-01.png" />
        </td>
        <td class="order-step-line" width="250px"></td>
        <td>
            <img src="/img/10-qwe-01.png" />
        </td>
    </tr>
    <tr>
        <td valign="top">
            <?php
            echo $this->formRow($form->get('user_name')).'<br/>';
            echo $this->formRow($form->get('user_address')).'<br/>';
            echo $this->formRow($form->get('user_phone')).'<br/>';
            ?>
        </td>
        <td></td>
        <td>
            <table>
<?php
    foreach($order_collection as $item){
?>
                <tr>
                    <td>
                        <b><?=$item->item_id;?>::<?=$item->item_name;?></b>
                    </td>
                    <td>
                        <span class="zf-green"><b>&nbsp;<?=$item->item_quantity;?>&nbsp;</b></span>
                    </td>
                    <td class="item-img-preview-50">
                        <img src="<?=Collection\Model\Collection::COLL_IMG_PATH.$item->img_link;?>" />
                    </td>
                    <td>
                        <span class="zf-green"><b>&nbsp;<?=$item->item_price;?>&nbsp;$</b></span>
                    </td>
                </tr>
<?php
    }
?>
            </table>
        </td>
        <td></td>
        <td>
            <table class="order-payment">
                <th colspan="2"> Credit cart </th>
                <tr>
                    <td> Visa </td>
                    <td><input type="radio" name="payment" value="visa" required="true" /></td>
                </tr>
                <tr>
                    <td> MasterCard </td>
                    <td><input type="radio" name="payment" value="mastercard" required="true" /></td>
                </tr>
                <th colspan="2"> Payment system </th>
                <tr>
                    <td> WebMoney </td>
                    <td><input type="radio" name="payment" value="webmoney" required="true" /></td>
                </tr>
                <tr>
                    <td> PayPal </td>
                    <td><input type="radio" name="payment" value="paypal" required="true" /></td>
                </tr>
                <th colspan="2"> Cash on delivery </th>
                <tr>
                    <td> Home </td>
                    <td><input type="radio" name="payment" value="home" required="true" /></td>
                </tr>
                <tr>
                    <td> Store </td>
                    <td><input type="radio" name="payment" value="store" required="true" /></td>
                </tr>
            </table>
        </td>
        <td></td>
    </tr>
    <tr><td colspan="6"><hr></td></tr>
    <tr>
        <td>cart id: <?=$this->cart_id;?></td>
        <td></td>
        <td>
            <h4><b>now total price of your cart is&nbsp;<span id="order-total-price" class="zf-green"><?=$this->total_price;?></span>&nbsp;$</b></h4>
        </td>
        <td colspan="3">
            <?php
            echo $this->formElement($form->get('checkbox')->setAttribute('required','true'));
            echo ' I agree with<a> sell and shipping rules </a><br/ >';
            echo $this->formElement($form->get('submit'));
            ?>
        </td>
    </tr>
</table>
<?=$this->form()->closeTag($form);?>