
<table id="order-table" cellpadding="0">
    <th>
        <h1><span class="zf-green">step1</span> : <br />Your profile</h1>
    </th>
    <th></th>
    <th>
        <h1><span class="zf-green">step2</span> : <br />Check your order</h1>
    </th>
    <th></th>
    <th>
        <h1><span class="zf-green">step3</span> : <br />Payment</h1>
    </th>
    <th></th>
    <tr>
        <td class="order-step-line"></td>
        <td>
            <img src="/img/10-qwe-01.png" />
        </td>
        <td class="order-step-line"></td>
        <td>
            <img src="/img/10-qwe-01.png" />
        </td>
        <td class="order-step-line"></td>
        <td>
            <img src="/img/10-qwe-01.png" />
        </td>
    </tr>
    <tr>
        <td valign="top">
            <?php
            $form = $this->order_form;

            $form->prepare();
            //$form->setAttribute('action', array('controller'=>'','action'=>''));

            echo $this->form()->openTag($form);

            echo $this->formLabel($form->get('name'));
            echo $this->formElement($form->get('name'));

            echo $this->formLabel($form->get('address'));
            echo $this->formElement($form->get('address'));

            echo $this->formLabel($form->get('phone'));
            echo $this->formElement($form->get('phone'));

            echo $this->form()->closeTag($form);
            ?>
        </td>
        <td></td>
        <td>
            <table>
                <?php
                    foreach($order_collection as $item){
                ?>
                <tr>
                    <td>
                        <b><?=$item->item_name;?></b>
                    </td>
                    <td>
                        <span class="zf-green"><b>&nbsp;<?=$item->item_quantity;?>&nbsp;</b></span>
                    </td>
                    <td class="item-img-preview-50">
                        <img src="<?=Collection\Model\Collection::COLL_IMG_PATH.$item->img_link;?>" />
                    </td>
                    <td>
                        <span class="zf-green"><b>&nbsp;<?=$item->item_price;?>&nbsp;$</b></span>
                    </td>
                </tr>
                <?php
                    }
                ?>
            </table>
        </td>
        <td></td>
        <td>

            <table class="order-payment">
                <th colspan="2"> Credit cart </th>
                <tr>
                    <td> Visa </td>
                    <td><input type="radio" name="gr1" value="visa"/><br /></td>
                </tr>
                <tr>
                    <td> MasterCard </td>
                    <td><input type="radio" name="gr1" value="mastercard"/><br /></td>
                </tr>
                <th colspan="2"> Payment system </th>
                <tr>
                    <td> WebMoney </td>
                    <td><input type="radio" name="gr1" value="webmoney"/><br /></td>
                </tr>
                <tr>
                    <td> PayPal </td>
                    <td><input type="radio" name="gr1" value="paypal"/><br /></td>
                </tr>
                <th colspan="2"> Cash on delivery </th>
                <tr>
                    <td> Home </td>
                    <td><input type="radio" name="gr1" value="home"/><br /></td>
                </tr>
                <tr>
                    <td> Store </td>
                    <td><input type="radio" name="gr1" value="store"/><br /></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr><td colspan="6"><hr></td></tr>
    <tr>
        <td></td>
        <td></td>
        <td>
            <h4><b>now total price of your cart is&nbsp;<span id="order-total-price" class="zf-green"><?=$this->total_price;?></span>&nbsp;$</b></h4>
        </td>
        <td colspan="3">
            <?php
            echo $this->formElement($form->get('checkbox'));
            echo ' I agree with sell and shipping rules ';
            echo $this->formElement($form->get('submit'));
            ?>
        </td>
    </tr>
</table>
