<?php
$flash = $this->flashMessenger();
?>
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <section class="login">
    <h2>Login</h2>
<?php echo $flash->render('NotLogin');?>
<?php echo $flash->render('ip_exist');?>
        <?php  ;?>
<?php if ($this->error): ?>
        <p class="error">
            There were one or more issues with your submission.
            Please correct them as indicated below.
        </p>
<?php endif ?>
<?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array(
        'controller' => 'Login',
        'action' => 'process'
    )));
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('user_email')).'<br />';
    echo $this->formRow($form->get('user_password')).'<br />';
    echo $this->formRow($form->get('login')->setAttribute('class','btn btn-success pull'));
    echo $this->form()->closeTag($form);
?>
        <a><strike>forgot your login / password?</strike></a>
    </section>
</body>
</html>