<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        //Kirill
                        ->prependStylesheet($this->basePath('slider/ItemSlider/css/style.css')) ?>
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        // Kirill
       //   ->prependFile($this->basePath('js/jquery-ui.min.js'));
            ->prependFile($this->basePath('js/customk.js'))
            ->prependFile($this->basePath('slider/ItemSlider/js/jquery.catslider.js'))
            ->prependFile($this->basePath('slider/ItemSlider/js/modernizr.custom.63321.js'))
        // Kirill
            ->prependFile($this->basePath('js/jquery-2.1.4.min.js'))
        ;?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img src="<?php echo $this->basePath('img/zf2-my-logo-2.png') ?>" alt="Zend Framework 2"/>&nbsp;MyStore<?php //echo $this->translate('Skeleton Application') ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <!--<li class="active"><a href="<?php echo $this->url('home') ?>"><?php //echo $this->translate('Home') ?></a></li>-->
                        <li class="my-active"><a href="<?php echo $this->url('users') ?>"><?php echo $this->translate('join') ?></a></li>
                        <li class="my-active"><a href="<?php echo $this->url('collection') ?>"><?php echo $this->translate('Collection') ?></a></li>
                        <li class="my-active"><?php echo $this->identity()->user_email;?></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> бай зенд текнологиес лтд. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
