<?php
if($this->identity()->user_role != 'admin'){
    header("Location: /admin");
    exit();
?>
    <a href="<?php echo $this->url('admin', array(
        'controller' => 'Auth', 'action' => 'logoutMe'));?>"> [ to login ]</a><br />
<?php
    die();
}
echo $this->headTitle('Adminka');
?>
    <span class=""><?php echo $this->identity()->user_email;?></span>
    <a href="<?php echo $this->url('admin', array(
        'controller' => 'Auth', 'action' => 'logoutMe'));?>"> [ logout ]</a><br />
    <a class="admin-menu-link" href="<?php echo $this->url('index', array(
        'controller'=>'Index', 'action'=>'index'));?>">[ main ]</a>
    <a class="admin-menu-link" href="<?php echo $this->url('collection-manager', array(
        'controller'=>'CollectionManager', 'action'=>'index'));?>">[ collection ]</a>
    <a class="admin-menu-link" href="">[ orders ]</a>
    <a class="admin-menu-link" href="<?php echo $this->url('user-manager', array(
        'controller'=>'Index', 'action' => 'index'));?>">[ users ]</a>
    <hr/>
<div class="content"><?php echo $this->content; ?></div>
